spring.application.name=bookexchange

spring.datasource.url=jdbc:postgresql://localhost:5432/book_exchange
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
